name: ci/cd

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**.md"
      - "**.org"

jobs:
  # lint-go:
  #   strategy:
  #     matrix:
  #       go-version: [1.19.x, 1.20.x]
  #       platform: [ubuntu-latest]

  #   runs-on: ${{ matrix.platform }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{ matrix.go-version }}
  #     - uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.53
  #         args: --timeout=5m

  build-docker:
    #  needs: lint-go
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - uses: imjasonh/setup-ko@v0.6
      - run: ko build -B ./
        env:
          KO_DOCKER_REPO: ghcr.io/dearrude
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
